name: hypixel_dart
description: An asynchronous wrapper for the Hypixel Network API
version: 0.0.7
environment:
  sdk: '>=2.0.0 <3.0.0'
repository: https://github.com/Eros/Hypixel-Dart
dependencies:
  http: ^0.12.2